### ISSUE TITLE
[HUD] Opção de analógico sempre no centro

### ISSUE THREAD

**Issue by electricjokebox** [tecMTST/jogo-mobiliza-sp#14]
- Na versão atual, o analógico do jogo aparece no ponto da tela onde o jogador clica;
- Disponibilizar a possibilidade do analógico sempre estar no centro (jogador) para testes de gameplay;
- Se possível deixar ele mais transparente nesse modo;

**Comment by rodigu** [comment]
`modo_estatico` no componente da alavanca

**Comment by electricjokebox** [comment]
Deu bão, só preciso jogar no celular agora.

**Comment by electricjokebox** [comment]
@rodigu a gente pode voltar para o analógico não fixo mesmo. No celular a jogabilidade ficou ruim.
