### ISSUE TITLE
[HUD] Ícone de Ranking

### ISSUE THREAD

**Issue by electricjokebox** [tecMTST/jogo-mobiliza-sp#16]
- Conforme reunião do dia 06/08/2024, adicionar mais um elemento do HUD, o "ranking" do jogador;
- O ícone do ranking ficará logo acima do mobilizômetro, do lado direito da tela, reservar um sprite quadrado;
- Ele terá 4 rankings (nome placeholder):
1. Panfleteiro (inicial)
2. Mobilizador (após a entrega de 5 pessoas)
3. Coordenador de Banca (após a entrega de 20 pessoas)
4. Líder de Grupo (acima de 50 pessoas)

**Comment by electricjokebox** [comment]
Falta adicionar os outros ícones:
![image](https://github.com/user-attachments/assets/a0ac6dc6-5eab-4e77-aa6b-145c50a28478)
![image](https://github.com/user-attachments/assets/8fc9d569-54dc-4bed-b7f1-ba7faabee276)

**Comment by rodigu** [comment]
so tinha um logo nos arquivos do Duarte, @dosgabrielbrito

**Comment by duartesoueu** [comment]
Segue todos os icones no tamanho certo (pode substituir o primeiro tbm, por favor): 

![mobilizometro_icone_4.png](https://github.com/user-attachments/assets/e73b96bb-fb91-4997-a5e1-fd84299fad7c)

![mobilizometro_icone.png](https://github.com/user-attachments/assets/a57ff192-deba-4cd9-9e09-bea6c869118f)

![mobilizometro_icone_3.png](https://github.com/user-attachments/assets/ddee896d-8b52-44b8-8be0-43271127b822)

![mobilizometro_icone_2.png](https://github.com/user-attachments/assets/94f53c81-ea1a-48c4-a07b-de1c9fec349d)
