### ISSUE TITLE
[GAMEDESIGN] Mudar a lógica da entrega das pessoas no ponto

### ISSUE THREAD

**Issue by electricjokebox** [tecMTST/jogo-mobiliza-sp#22]
- O ponto antes da entrega das pessoas deve aparecer na cor CINZA e com outro asset de arte para mostrar um local "triste" e "desanimado";
- Quando o ponto é recuperado com a entrega de pessoas o asset de arte deve mudar para o asset original COLORIDO do ponto "barraca de panfleto", "ato" ou "comicio";

**Comment by electricjokebox** [comment]
![image](https://github.com/user-attachments/assets/f9c42a26-e9de-4127-be88-d335967079ba)

- Texto para Barraca de Panfletos: "BARRACA DE PANFLETOS DA CAMPANHA MOBILIZADA!"
- Texto para Ato: "MARCHA COM BOULOS E MARTA MOBILIZADA!"
- Texto para Comício: "COMÍCIO DA VITÓRIA MOBILIZADO!"

**Comment by rodigu** [comment]
Nao acho q botar texto vale a pena. Vai ficar ocupado de mais a tela

**Comment by electricjokebox** [comment]
Sem texto então, tranquilo! Faltam só os assets do Duarte.
