### ISSUE TITLE
[BUG] Botão "Jogar novamente" levando para o mapa antigo

### ISSUE THREAD

**Issue by electricjokebox** [tecMTST/jogo-mobiliza-sp#26]
Ao terminar o jogo e reiniciar, o mapa do jogo antigo está sendo carregado.

**Comment by rodigu** [comment]
nao consegui reproduzir

**Comment by electricjokebox** [comment]
Segue video explicativo:
https://github.com/user-attachments/assets/c792cee0-a79e-4c33-bc24-2741894fbf13

**Comment by electricjokebox** [comment]
Reabrindo prq fechei sem querer.
