### ISSUE TITLE
[HUD] Mobilizômetro

### ISSUE THREAD

**Issue by electricjokebox** [tecMTST/jogo-mobiliza-sp#8]
- Mobilizômetro será a barra de progresso que ficará na posição inferior da tela;
- Seu valor máximo é o total de pessoas no mapa, que coincide com o valor total máximo dos eventos (atualmente 125);
- Conforme o avanço do jogador na mobilização de pessoas, a cor da barra vai se intensificando;
- Deve possuir um indicador de seu valor internamente ou ao lado;
- Ao atingir seu valor máximo ele deve mostrar uma mensagem (placeholder: "CIDADE 100% MOBILIZADA!");

![I1](https://github.com/user-attachments/assets/8c8b479e-685f-4105-9f15-d82f6df7b5d0)

**Comment by rodigu** [comment]
icone do lado esquerdo do mobilizometro
tint textura de progresso
